CREATE TABLE cards
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    card_number BYTEA       NOT NULL,
    expire      BYTEA       NOT NULL,
    cvv_hash    TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cards_user_id ON cards (user_id);


