CREATE TABLE credits
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id    BIGINT         NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    principal     NUMERIC(12, 2) NOT NULL,
    interest_rate NUMERIC(5, 4)  NOT NULL,
    term_months   INT            NOT NULL,
    start_date    DATE           NOT NULL,
    status        VARCHAR(20)    NOT NULL DEFAULT 'active',
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_credits_account_id ON credits (account_id);
