CREATE TABLE transactions
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT         NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    amount     NUMERIC(12, 2) NOT NULL,
    type       VARCHAR(20)    NOT NULL,
    status     VARCHAR(20)    NOT NULL DEFAULT 'completed',
    created_at TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_transactions_account_id ON transactions (account_id);
